openapi: '3.0.0'
info:
  title: kytos/flow_manager
  version: 0.2.1
  description: >-
    **Warning**: *This documentation is experimental and may change soon.*


    Manages flows for OpenFlow switches, for versions 1.0 and 1.3. Can add, list
    and remove flows from datapaths. Currently supports a subset of available
    matches and actions from the OpenFlow specification.
tags:
  - name: List
  - name: Add
  - name: Delete
paths:
  /api/kytos/flow_manager/flows:
    get:
      tags:
        - List
      summary: Retrieve a list of all flows from all known datapaths.
      responses:
        '200':
          description: Operation Successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flows'
    post:
      tags:
        - Add
      summary: Insert flows in all known datapaths.
      parameters:
        - in: body
          name: body
          description: List of flows to be inserted.
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SetFlow'
      consumes:
        - application/json
      responses:
        '202':
           description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
  '/api/kytos/flow_manager/flows/{dpid}':
    get:
      tags:
        - List
      summary: Retrieve a list of all flows from a single datapath.
      parameters:
        - name: dpid
          in: path
          required: true
          type: string
          description: DPID of the target datapath.
      responses:
        '200':
          description: Operation Successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flows'
        '404':
          description: Datapath not found.
    post:
      tags:
        - Add
      summary: Insert flows in a single datapath.
      parameters:
        - in: body
          name: body
          description: List of flows to be inserted.
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SetFlow'
        - name: dpid
          in: path
          required: true
          type: string
          description: DPID of the target datapath.
      consumes:
        - application/json
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
        '404':
          description: Datapath not found.
  /api/kytos/flow_manager/delete:
    post:
      tags:
        - Delete
      summary: Remove matching flows from all known datapaths.
      parameters:
        - in: body
          name: body
          description: Parameters of flows to be removed. The NApp will send a FlowMod message requesting the removal of flows with those parameters.
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/DeleteFlow'
      consumes:
        - application/json
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
  '/api/kytos/flow_manager/delete/{dpid}':
    post:
      tags:
        - Delete
      summary: Remove matching flows from a single datapath.
      parameters:
        - in: body
          name: body
          description: Parameters of flows to be removed. The NApp will send a FlowMod message requesting the removal of flows with those parameters.
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/DeleteFlow'
        - name: dpid
          in: path
          required: true
          type: string
          description: DPID of the target datapath.
      consumes:
        - application/json
      responses:
        '202':
          description: FlowMod messages sent.
        '400':
           description: Invalid JSON flow.
        '404':
          description: Datapath not found.

components:
  schemas:
    Match:
      type: object
      properties:
        in_port:
          type: integer
          format: int64
          example: 2
        dl_src:
          type: string
          example: '00:1f:3a:3e:9a:cf'
        dl_dst:
          type: string
          example: '00:15:af:d5:38:98'
        dl_type:
          type: integer
          format: int64
          example: 2048
        dl_vlan:
          type: integer
          format: int64
          example: 300
        dl_vlan_pcp:
          type: integer
          format: int64
          example: 0
    Actions:
      type: object
      properties:
        set_vlan:
          type: integer
          format: int64
          example: 450
        output:
          type: integer
          format: int64
          example: 3
    Flow:
      type: object
      properties:
        table_id:
          type: integer
          format: int64
          example: 0
        priority:
          type: integer
          format: int64
          example: 10
        idle_timeout:
          type: integer
          format: int64
          example: 360
        hard_timeout:
          type: integer
          format: int64
          example: 1200
        cookie:
          type: integer
          format: int64
          example: 84114904
        match:
          $ref: '#/components/schemas/Match'
        actions:
          $ref: '#/components/schemas/Actions'
    Flows:
      type: object
      properties:
        '00:00:00:00:00:00:00:01':
          type: array
          items:
            $ref: '#/components/schemas/Flow'
    SetMatch:
      type: object
      properties:
        in_port:
          type: integer
          format: int64
          example: 5
        dl_vlan:
          type: integer
          format: int64
          example: 110
    SetFlow:
      type: object
      properties:
        priority:
          type: integer
          format: int64
          example: 10
        cookie:
          type: integer
          format: int64
          example: 40941148
        match:
          $ref: '#/components/schemas/SetMatch'
        actions:
          $ref: '#/components/schemas/Actions'
    DeleteFlow:
      type: object
      properties:
        cookie:
          type: integer
          format: int64
          example: 84114904
        priority:
          type: integer
          format: int64
          example: 10
        match:
          type: object
          properties:
            dl_src:
              type: string
              example: '00:0a:0b:c2:12:16'
